name: Merge to main
on:
    push:
        branches:
            - main

jobs:
    get_version:
        name: "Get package.json version"
        uses: whereby/github-actions/.github/workflows/check_if_version_is_incremented.yml@1.0.0
        with:
            source_dir: src
    draft_release:
        if: needs.get_version.outputs.new_version
        needs: get_version
        name: "Draft release"
        uses: whereby/github-actions/.github/workflows/draft_release.yml@1.0.0
        with:
            tag_name: "${{ needs.get_version.outputs.new_version }}"
